name = "lean-rust-parser"
defaultTargets = ["LeanRustParser"]
testDriver = "LeanRustParserTestsExe"

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[lean_lib]]
name = "LeanRustParser"
supportInterpreter = true

[[lean_lib]]
name = "LeanRustParserTests"
globs = ["LeanRustParserTests.+"]
supportInterpreter = true

[[lean_exe]]
name = "LeanRustParserTestsExe"
root = "LeanRustParserTests.Main"
supportInterpreter = true
