module

public import LeanRustParser.ParserElabForTests

@[expose] public section

def literalsTests : List (String × String × String) := [
--   ("integer literals",
--     ppSourceFile (rust
--       0;
--       0___0;
--       123;
--       0usize;
--       123i32;
--       123u32;
--       123_u32;
--       0xff_u8;
--       0o70_i16;
--       0b1111_1111_1001_0000_i32;
--       1u128;
--     end),
--     r#"0;
-- 0___0;
-- 123;
-- 0usize;
-- 123i32;
-- 123u32;
-- 123_u32;
-- 0xff_u8;
-- 0o70_i16;
-- 0b1111_1111_1001_0000_i32;
-- 1u128;"#),
--   ("floating-point literals",
--     ppSourceFile (rust
--       123.123;
--       2.;
--       123.0f64;
--       0.1f64;
--       0.1f32;
--       12E+99_f64;
--     end),
--     r#"123.123;
-- 2.;
-- 123.0f64;
-- 0.1f64;
-- 0.1f32;
-- 12E+99_f64;"#),
--   ("string literals",
--     ppSourceFile (rust
--       "";
--       "abc";
--       c"foo";
--       b"foo\nbar";
--       "foo\
--           bar";
--       "\"foo\"";
--       "/* foo bar */ foo bar";
--       "foo\x42\x43bar";
--       "foo \x42  \x43 bar";
--     end),
--     r#""";
-- "abc";
-- c"foo";
-- b"foo\\nbar";
-- "foo\\
--     bar";
-- "\\"foo\\"";
-- "/* foo bar */ foo bar";
-- "foo\\x42\\x43bar";
-- "foo \\x42  \\x43 bar";"#),
--   ("raw string literals",
--     ppSourceFile (rust
--       r#"abc"#; r##"ok"##;
--       r##"foo #"# bar"##;
--       r###"foo ##"## bar"###;
--       r######"foo ##### bar"######;
--     end),
--     r#"r#"abc"#; r##"ok"##;
-- r##"foo #"# bar"##;
-- r###"foo ##"## bar"###;
-- r######"foo ##### bar"######;"#),
--   ("raw byte string literals",
--     ppSourceFile (rust
--       br#"abc"#;
--       br##"abc"##;
--     end),
--     r#"br#"abc"#;
-- br##"abc"##;"#),
--   ("raw c string literals",
--     ppSourceFile (rust
--       cr#"abc"#;
--       cr##"abc"##;
--     end),
--     r#"cr#"abc"#;
-- cr##"abc"##;"#),
--   ("character literals",
--     ppSourceFile (rust
--       'a';
--       '\'';
--       '\0';
--       b'x';
--       '\t';
--       '\xff';
--       '\\';
--     end),
--     r#"'a';
-- '\\'';
-- '\\0';
-- b'x';
-- '\\t';
-- '\\xff';
-- '\\\\';"#),
--   ("boolean literals",
--     ppSourceFile (rust
--       true;
--       false;
--     end),
--     r#"true;
-- false;"#)
]
